### ISSUE TITLE
Incorrect checksums

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#3] opened 2022-05-14 13:50 UTC
The current code writes NAV-PVT sentences with incorrect checksums for points that are filtered (the speed is set to 0 because of fewer than 5 satellites, sAcc > 1m/s, or speed >40 m/s). These sentences are then rejected by readers that check the checksum, which includes u-center and GPS Speedreader.

The cause is that the filtering is done before writing the sentences to log files. The problem could very simply be fixed by first writing the data to the log file, and then applying the filters. The filters make sense for internal speed calculations, but the log files should contain the original information from the GPS chip, not data that have been altered in any way by the firmware.

**Comment by RP6conrad** [comment] 2022-05-14 13:57
Yes, this has to be corrected. I’ll change it with the next update. 

Greetings Jan.

Verzonden vanuit Mail voor Windows

Van: prichterich
Verzonden: zaterdag 14 mei 2022 15:51
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] Incorrect checksums (Issue #3)

The current code writes NAV-PVT sentences with incorrect checksums for points that are filtered (the speed is set to 0 because of fewer than 5 satellites, sAcc > 1m/s, or speed >40 m/s). These sentences are then rejected by readers that check the checksum, which includes u-center and GPS Speedreader.
The cause is that the filtering is done before writing the sentences to log files. The problem could very simply be fixed by first writing the data to the log file, and then applying the filters. The filters make sense for internal speed calculations, but the log files should contain the original information from the GPS chip, not data that have been altered in any way by the firmware.

**Closed** 2023-01-18 11:31 UTC
